# Generated by Django 2.0.7 on 2019-02-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=200)),
                ('education', models.IntegerField(default=0)),
                ('vis', models.IntegerField(default=0)),
                ('news', models.IntegerField(default=0)),
                ('isFinish', models.BooleanField(default=False)),
                ('passTrap', models.BooleanField(default=False)),
                ('valid1', models.CharField(default='', max_length=200)),
                ('valid2', models.CharField(default='', max_length=200)),
                ('session_id', models.CharField(default='', max_length=200)),
                ('token', models.CharField(default='', max_length=200)),
                ('a1des', models.CharField(default='', max_length=200)),
                ('a2des', models.CharField(default='', max_length=200)),
                ('a1q2', models.IntegerField(default=0)),
                ('a1q3', models.IntegerField(default=0)),
                ('a1q4', models.IntegerField(default=0)),
                ('a1q5', models.IntegerField(default=0)),
                ('a1q6', models.IntegerField(default=0)),
                ('a1q1', models.IntegerField(default=0)),
                ('a2q2', models.IntegerField(default=0)),
                ('a2q3', models.IntegerField(default=0)),
                ('a2q4', models.IntegerField(default=0)),
                ('a2q5', models.IntegerField(default=0)),
                ('a2q6', models.IntegerField(default=0)),
            ],
        ),
    ]
