# Generated by Django 2.0.7 on 2019-02-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turk', '0002_predictanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictanswer',
            name='a1q1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a1q2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a1q3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a1q4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a1q5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a1q6',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a2q2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a2q3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a2q4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a2q5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='a2q6',
            field=models.CharField(default='', max_length=200),
        ),
    ]
