# Generated by Django 2.0.7 on 2019-02-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turk', '0003_auto_20190221_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictanswer',
            name='a2q1',
            field=models.CharField(default='', max_length=200),
        ),
    ]
