# Generated by Django 2.0.7 on 2021-08-10 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turk', '0004_predictanswer_a2q1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=200)),
                ('education', models.IntegerField(default=0)),
                ('vis', models.IntegerField(default=0)),
                ('news', models.IntegerField(default=0)),
                ('isFinish', models.BooleanField(default=False)),
                ('passTrap', models.BooleanField(default=True)),
                ('session_id', models.CharField(default='', max_length=200)),
                ('token', models.CharField(default='', max_length=200)),
                ('turkID', models.CharField(default='', max_length=200)),
                ('q1', models.CharField(default='', max_length=150)),
                ('trap', models.CharField(default='', max_length=100)),
                ('q2', models.CharField(default='', max_length=300)),
                ('q3a', models.CharField(default='', max_length=300)),
                ('q3b', models.CharField(default='', max_length=300)),
                ('q3c', models.CharField(default='', max_length=300)),
                ('q3d', models.CharField(default='', max_length=300)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=200)),
                ('education', models.IntegerField(default=0)),
                ('vis', models.IntegerField(default=0)),
                ('news', models.IntegerField(default=0)),
                ('isFinish', models.BooleanField(default=False)),
                ('passTrap', models.BooleanField(default=False)),
                ('valid', models.CharField(default='', max_length=200)),
                ('session_id', models.CharField(default='', max_length=200)),
                ('token', models.CharField(default='', max_length=200)),
                ('turkID', models.CharField(default='', max_length=200)),
                ('tn', models.IntegerField(default=0)),
                ('d1q1', models.IntegerField(default=0)),
                ('d1q2', models.IntegerField(default=0)),
                ('d1q3', models.IntegerField(default=0)),
                ('d2q1', models.IntegerField(default=0)),
                ('d2q2', models.IntegerField(default=0)),
                ('d2q3', models.IntegerField(default=0)),
                ('d3q1', models.IntegerField(default=0)),
                ('d3q2', models.IntegerField(default=0)),
                ('d3q3', models.IntegerField(default=0)),
                ('d4q1', models.IntegerField(default=0)),
                ('d4q2', models.IntegerField(default=0)),
                ('d4q3', models.IntegerField(default=0)),
                ('d5q1', models.IntegerField(default=0)),
                ('d5q2', models.IntegerField(default=0)),
                ('d5q3', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('checkval1', models.IntegerField(default=0)),
                ('checkval2', models.IntegerField(default=0)),
                ('checkval3', models.IntegerField(default=0)),
                ('checkval4', models.IntegerField(default=0)),
                ('checkval5', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='predictanswer',
            old_name='a1des',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='predictanswer',
            old_name='a1q1',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='predictanswer',
            old_name='a1q2',
            new_name='q3',
        ),
        migrations.RenameField(
            model_name='predictanswer',
            old_name='a1q3',
            new_name='q4',
        ),
        migrations.RenameField(
            model_name='predictanswer',
            old_name='a1q4',
            new_name='q5',
        ),
        migrations.RenameField(
            model_name='predictanswer',
            old_name='a1q5',
            new_name='q6',
        ),
        migrations.RenameField(
            model_name='predictanswer',
            old_name='a1q6',
            new_name='turkID',
        ),
        migrations.RenameField(
            model_name='predictanswer',
            old_name='a2des',
            new_name='valid',
        ),
        migrations.RemoveField(
            model_name='predictanswer',
            name='a2q1',
        ),
        migrations.RemoveField(
            model_name='predictanswer',
            name='a2q2',
        ),
        migrations.RemoveField(
            model_name='predictanswer',
            name='a2q3',
        ),
        migrations.RemoveField(
            model_name='predictanswer',
            name='a2q4',
        ),
        migrations.RemoveField(
            model_name='predictanswer',
            name='a2q5',
        ),
        migrations.RemoveField(
            model_name='predictanswer',
            name='a2q6',
        ),
        migrations.RemoveField(
            model_name='predictanswer',
            name='valid1',
        ),
        migrations.RemoveField(
            model_name='predictanswer',
            name='valid2',
        ),
        migrations.RemoveField(
            model_name='rankanswer',
            name='check1chart1',
        ),
        migrations.RemoveField(
            model_name='rankanswer',
            name='check1chart2',
        ),
        migrations.RemoveField(
            model_name='rankanswer',
            name='check2chart1',
        ),
        migrations.RemoveField(
            model_name='rankanswer',
            name='check2chart2',
        ),
        migrations.AddField(
            model_name='predictanswer',
            name='des',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='predictanswer',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictanswer',
            name='help1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictanswer',
            name='help2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictanswer',
            name='help3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictanswer',
            name='q7',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='predictanswer',
            name='tn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictanswer',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankanswer',
            name='nonsenseNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictanswer',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(18)]),
        ),
    ]
